name: Run tests
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.1
      - run: gem install bundler -v 2.2.21
      - run: bin/setup
      - run: bin/rspec
